### ISSUE TITLE
"rationalize" pkg/utf and char_encodings in pkg/html

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/convert#1]
https://github.com/dart-lang/utf
https://github.com/dart-lang/html/blob/master/lib/src/char_encodings.dart

I'd argue these all should be in pkg/convert. Perhaps we should deprecate pkg/utf

**Comment by lrhn** [comment]
The `utf` package is really a dumping ground for pre-`dart:convert` UTF-8 functions from the platform library `dart:utf`. It allows code written prior to the introduction of `dart:convert` to keep using, if they just import `package:utf/utf.dart` instead of the no-longer-existing `dart:utf`.
As such, it is not being actively developed, and integrating it into `package:convert` does not make sense (it is not in the form of a converter). It should probably be deprecated.

**Comment by kevmoo** [comment]
Happily. pkg:html no longer depends on pkg:utf. I think this can be closed.

**Comment by kevmoo** [comment]
👍 to discontinuing pkg:utf, btw
